github actions; all projects
coveooss/coveo-python-oss pull request #11
Opened 2021-01-28 22:15 UTC by jonapich

This enables tests and publish on all projects.

There's a really weird behavior on mac where `platform.node()` changes from a `.` to a `-` mid execution. 🤷🏻‍♂️ 

Other than that, even though docker is installed on github action machines, they're configured for non-linux containers. The docker tests will fail trying to build the dockerfile. So I skipped those tests unless we're on linux.

The readmes were created just for the sake of the pyproject.toml and will be updated through #10

2021-01-30 23:54 UTC, klalumiere requested changes
I'm quite uncomfortable with the 8 copy pastes. A single update will take 9 times longer to write and will also be longer to review. Moreover, if you add more packages, like `coveo-magic`, well that's a copy-paste more. We should at least discuss the possibility to use a local action with parameterized name. A typical counterargument against this approach is

>Yeah, but what if I want to make `.github/workflows/coveo-systools.hml` different?

and the counterargument to that counterargument is that, of course, you can. Once the local action is written, you still have the option to use it _or not_.

2021-01-30 23:54 UTC, klalumiere commented on coveo-testing/tests_testing/test_test_id.py
> +_ = unique_test_id  # mark fixtures are used
Did you mean

```suggestion
_ = unique_test_id  # mark fixtures as used

```
?
(I feel like an auto-correct :laughing:)

2021-01-30 23:54 UTC, klalumiere commented on .github/workflows/coveo-itertools.yml
> +          dry-run: ${{ github.ref != 'refs/heads/main' }}
I'm starting to guess that I'll review the same workflow with different `name` and `paths`. Perhaps you can write a local composite-action with parameterized `name`? I think you'd reap the benefit after you decide to update the workflows 2-3 times (for instance to update `python-version`).

2021-02-01 17:07 UTC, jonapich commented
> I'm quite uncomfortable with the 8 copy pastes. A single update will take 9 times longer to write and will also be longer to review. Moreover, if you add more packages, like `coveo-magic`, well that's a copy-paste more. We should at least discuss the possibility to use a local action with parameterized name. A typical counterargument against this approach is
> 
> >Yeah, but what if I want to make `.github/workflows/coveo-systools.hml` different?
> 
> and the counterargument to that counterargument is that, of course, you can. Once the local action is written, you still have the option to use it _or not_.

Originally I wanted to do composites but it was more problems than not. Is the "local action" à composite? For instance I couldn't call uses: python setup from a composite.

2021-02-02 15:41 UTC, klalumiere commented
> > I'm quite uncomfortable with the 8 copy pastes. A single update will take 9 times longer to write and will also be longer to review. Moreover, if you add more packages, like `coveo-magic`, well that's a copy-paste more. We should at least discuss the possibility to use a local action with parameterized name. A typical counterargument against this approach is
> > > Yeah, but what if I want to make `.github/workflows/coveo-systools.hml` different?
> > 
> > 
> > and the counterargument to that counterargument is that, of course, you can. Once the local action is written, you still have the option to use it _or not_.
> 
> Originally I wanted to do composites but it was more problems than not. Is the "local action" à composite? For instance I couldn't call uses: python setup from a composite.

C'est dommage ça. Il y a déjà un [issue](https://github.com/actions/runner/issues/438) d'ouvert qui demande qu'on puisse faire ça si tu veux faire +1 :-).

2021-02-02 15:43 UTC, klalumiere approved these changes

2021-02-03 19:50 UTC, merged